version: "3.3"
services:
  web:
    image: danceschool_web:latest
    deploy:
      replicas: 1
    env_file: env
    secrets:
      - postgres_url
      - django_secret_key
    volumes:
      - ./docker/web:/data/web
      - ./school:/data/web/school
    working_dir: /data/web/school
    command: /usr/bin/gunicorn school.wsgi:application -w 2 -b :8000

  nginx:
    image: danceschool_nginx:latest
    deploy:
      replicas: 1
    ports:
      - "80:80"
      - "443:443"

  postgres:
    image: postgres:latest
    deploy:
      replicas: 1
    volumes:
      - ./docker/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./backups/postgresql:/backup
      - data:/var/lib/postgresql
    env_file:
      - env
    secrets:
      - postgres_user
      - postgres_password

  redis:
    image: redis:latest
    deploy:
      replicas: 1

  huey:
    image: danceschool_web:latest
    deploy:
      replicas: 1
    env_file: env
    secrets:
      - postgres_url
      - django_secret_key
    volumes:
      - ./docker/web:/data/web
      - ./school:/data/web/school
    working_dir: /data/web/school
    command: python3 manage.py run_huey

volumes:
  data:

secrets:
  postgres_user:
    external: true
  postgres_password:
    external: true
  postgres_url:
    external: true
  django_secret_key:
    external: true
