version: "3.3"
services:
  web:
    image: danceschool_web:latest
    deploy:
      replicas: 1
    env_file: env
    secrets:
      - postgres_url
      - django_secret_key
    working_dir: /data/web
    # command: gunicorn school.wsgi:application -w 2 -b :8000
    command: top
    networks:
      danceschool_default:
        aliases:
          - web

  nginx:
    image: danceschool_nginx:latest
    deploy:
      replicas: 1
    ports:
      - "80:80"
      - "443:443"
    networks:
      danceschool_default:
        aliases:
          - nginx

  postgres:
    image: postgres:latest
    hostname: postgres
    deploy:
      replicas: 1
    volumes:
      - ./backups/postgresql:/backup
      - danceschool_postgres:/var/lib/postgresql/data
    env_file:
      - env
    secrets:
      - postgres_user
      - postgres_password
    networks:
      danceschool_default:
        aliases:
          - postgres

  redis:
    image: redis:latest
    hostname: redis
    deploy:
      replicas: 1
    networks:
      danceschool_default:
        aliases:
          - redis

  huey:
    image: danceschool_web:latest
    deploy:
      replicas: 1
    env_file: env
    secrets:
      - postgres_url
      - django_secret_key
    volumes:
      - ./docker/web:/data/web
      - ./school:/data/web/school
    working_dir: /data/web
    command: top
    # command: python3 manage.py run_huey
    networks:
      danceschool_default:
        aliases:
          - huey


volumes:
  danceschool_postgres:
  django_static_data:

networks:
  danceschool_default:
    driver: overlay

secrets:
  postgres_user:
    external: true
  postgres_password:
    external: true
  postgres_url:
    external: true
  django_secret_key:
    external: true
